#!/usr/bin/env bash

set -eu -o pipefail

# Add startup functions

add_content() {
  local file="$1"

  if [[ ! -f "$file" ]]; then
    return 1
  fi

  local start_marker end_marker content
  start_marker="#### BEGIN dotfiles MANAGED BLOCK"
  end_marker="### END dotfiles MANAGED BLOCK"

  content=$(
    cat << END_HEREDOC

$start_marker

$(curl -fsSL https://raw.githubusercontent.com/ljishen/dotfiles/master/.bashrc)

$end_marker
END_HEREDOC
  )

  # remove obsolete content
  sed -i "/$start_marker/,/$end_marker/d" "$file"

  # Delete all trailing blank lines at end of file
  #   http://sed.sourceforge.net/sed1line.txt
  sed -i -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$file"

  echo "$content" >> "$file"
}

add_content "$HOME/.bash_profile" || add_content "$HOME/.bash_login" || add_content "$HOME/.profile"

echo "Done!"
